### ISSUE TITLE
website restructure master tracking ticket

### ISSUE THREAD

**Issue by lucasgonze** [COVID19Tracking/website#125]
This is to bootstrap and coordinate work towards a major rewrite of the site structure. I'll call this project website-restructure. 

This is not only structure but also design. This rev will be the vehicle for the new design.

The requirements:
https://docs.google.com/document/d/1NPypuNap-yFaOpzd2SKkXbI9GnkzI5QOsozLACSBuww/edit

**Comment by schwartzadev** [comment]
Hey can you enable commenting on this document?

Thanks for sharing this here!

**Comment by lucasgonze** [comment]
This is an editable and commentable copy of the document:

https://docs.google.com/document/d/1Qamjso7vGSOFHHogQXu13QPwUnrvd_Tk-Du06EmZROE/edit?usp=sharing

**Comment by lucasgonze** [comment]
It would be very productive to make markups, whether in the form of wireframes or HTML.

**Comment by kissane** [comment]
Permissions updated on the main doc, let's kill that fork https://docs.google.com/document/d/1NPypuNap-yFaOpzd2SKkXbI9GnkzI5QOsozLACSBuww/edit

**Comment by kevee** [comment]
After discussion in #116 and in Slack, we decided to move ahead with using Gatsby for the website. I'm going to start a new `gatsby` branch that we can start that work from.

A working sample that just uses our existing design is up here for perf testing, it only has a homepage and the us-daily page:
https://distracted-darwin-ddf968.netlify.com/

**Comment by lucasgonze** [comment]
CTP Website Users/Goals

https://docs.google.com/document/d/1nMydLa_Ckj9MDyu6ooGRKeZx5OeAbI1q7lzDUKEr6rw/edit#heading=h.mrmpuq727hid

**Comment by kevee** [comment]
Components that are either just plain needed, or defined in the doc. I'm going to boilerplate these out and hook up a storybook so we can monitor.

- [ ] Accessibility utilities
- [ ] Skip content (probably reach skipnav)
- [ ] Header
- [ ] Footer
- [ ] Help/small text
- [ ] Secondary navigation
- [ ] Buttons (big, small)
- [ ] Lead paragraph
- [ ] Data visualization links
- [ ] Lists (UL, OL, UL unstyled)
- [ ] Table (support horizontal scroll in mobile)
- [ ] Visualization wrapper with associated data in table for a11y
- [ ] Company/supporter logo
- [ ]

**Comment by lucasgonze** [comment]
Moved "components" checklist to dedicated ticket, https://github.com/COVID19Tracking/website/issues/150

**Comment by lucasgonze** [comment]
Given that I have created a milestone and project, this tracking ticket has no purpose.
