### ISSUE TITLE
CRDT: Social Cards + New Data for Infection/Mortality Rates

### ISSUE THREAD

**Issue by neeshabeee** [COVID19Tracking/website#1452]
**Objective: Allow the general public to easily see how COVID-19 is impacting different race/ethnicity groups in their state.**

We will do this by:
* Providing new analysis about per capita rates for each race/ethnicity, for each state and nationwide
* Enabling people to share this information as a graphic and text, in order to help spread awareness

Sections below:
1. Outbound flow: Generate & share a graphic with others from the CTP website
2. Inbound flow: See a landing page & follow-up resources when coming to CTP from other websites
3. Copy to use when referring to different racial and ethnic groups
4. Logic for the graphic

**[Figma link is here](https://www.figma.com/file/GwkYSPVlTkdgLyGNgeMrLz/v3-Refresh?node-id=2183%3A85)**

---

### A) When I'm viewing the CRDT dashboard, I see a link to view per capita rates as a graphic:

![Screen Shot 2020-09-18 at 4 55 02 PM](https://user-images.githubusercontent.com/22971446/93653856-90bbe180-f9cf-11ea-8378-12e4d7e3e347.png)

* New copy introduced:

_Compare Florida's infection and mortality rates by race and ethnicity. View rates per capita as a graphic_

* This copy should not appear on the dashboard for the following territories (we're not supporting these right now): AS, GU, MP, VI

### B) I can generate and view a graphic and text that describes per capita rates by state. I can also share this information from the website.

![Screen Shot 2020-09-18 at 4 55 56 PM](https://user-images.githubusercontent.com/22971446/93654533-e2b23680-f9d2-11ea-980b-1f7f63013ecb.png)

**New page**
* /race/infection-and-mortality-rates
* Appears in global nav

**Page elements**
* Page title copy:

_Infection and Mortality Rates by Race and Ethnicity_

* Description copy 1:

_We compute the number of cases and deaths relative to population size for each race and ethnicity. This information helps identify which people are disproportionately being impacted by COVID-19 in every state._

* H2 copy:

_See the per capita rates by state_

* Description copy 2:

_Select a state or territory to see the latest information about COVID-19 cases and deaths per 100K people for each race and ethnicity. These charts are updated twice per week and use standard Census categories for race and ethnicity._

* Detail text copy:

_The data shown in these charts are reported by the state or territory and do not include those with race classified as "Other" or "Two or more races." Hispanic or Latino ethnicity may include any race._

* Dropdown picker: Excludes AS, GU, MP, VI from the list. Also includes **(All)** for All States/Nationwide stats -- which should appear first in the dropdown list ordering. (All) is the default selection, if the user has not already selected one.
* Graphic based on the dropdown selection. **See the final section for details/logic about the graphics & social media copy**
* Suggested social media text, for the selected state/territory option. **See final section for this logic too**
* Social media CTA copy:

_Share this directly on social media or download a square image for Instagram_ 

* Social media buttons for: Twitter, Facebook, and copy link. When using these buttons/links, suggested social media text is pre-populated and the selected graphic appears as the link preview/social card image

### C) When clicking a link for a state with per capita data available: I visit a landing page

![Screen Shot 2020-09-18 at 5 03 48 PM](https://user-images.githubusercontent.com/22971446/93654118-c90fef80-f9d0-11ea-86b0-03a3191b713c.png)

**Page elements**
* Page title copy: 

_{STATE}: Infection and mortality rates by race and ethnicity_
** Example: Florida: Infection and mortality rates by race and ethnicity

* Description copy:
* Use same copy logic as referenced above in "General header copy logic for the graphic"

* [Specified Graphic]

* More copy below the graphic:

_You can learn more about COVID-19 and its impact on different racial and ethnic groups by visiting these pages:_
_- The COVID Racial Data Tracker_
_- Racial Data Dashboard_
_- Infection and Mortality Rates by Race and Ethnicity_

### D) When clicking a link for a state with per capita data available: I visit /race/get-better-data to help advocate for better data

---

### Copy to use when referring to different racial and ethnic groups

**Copy to be used on Chart labels:**
* Black/African American
* Hispanic/Latino
* Asian
* Asian/Pacific Islander
* Native Hawaiian/Pacific Islander
* American Indian/Alaska Native
* White

**Copy to be used elsewhere, whenever {{GROUP}} is written:**
e.g., "In Hawaii, as of September 16, Asians/Pacific Islanders have the highest COVID-19 infection rates..."

* Black/African American people
* Hispanic/Latino people
* Asian people
* White people
* Asians/Pacific Islanders
* Native Hawaiians/Pacific Islanders
* American Indians/Alaska Natives

---

### Logic for the graphics & generated social media copy

Social media copy:
* Empty state social media copy: 

_In {{STATE}}, race and ethnicity information is still not reported for COVID-19 cases and deaths. Help us get better data by contacting health officials at https://covidtracking.com/race/get-better-data #RacialDataTracker_

* When only infection data is reported: 

_In {{STATE}}, as of {{MONTH AND DAY}}, {{GROUP}} had the highest risk of contracting #COVID19. Get the latest analysis: {{STATE LANDING PAGE LINK}} #RacialDataTracker_

* When only death data is reported: 

_In {{STATE}}, as of {{MONTH AND DAY}}, {{GROUP}} were most likely to have died from #COVID19. Get the latest analysis: {{STATE LANDING PAGE LINK}} #RacialDataTracker_

* When 2 different groups have highest infection and mortality rates:

 _In {{STATE}}, as of {{MONTH AND DAY}}, {{GROUP}} had the highest risk of contracting #COVID19. {{GROUP}} were most likely to have died. Get the latest analysis: {{STATE LANDING PAGE LINK}} #RacialDataTracker_

* When 1 group has both highest infection and mortality rates: 

_In {{STATE}}, as of {{MONTH AND DAY}}, {{GROUP}} had the highest risk of contracting #COVID19 and were most likely to have died. Get the latest analysis: {{LANDING PAGE LINK}} #RacialDataTracker_

** Header copy logic, for all cases where there's race/ethnicity data to show**
* 2 main copy scenarios (2 different groups have highest infection & mortality rate VS. 1 group has both)

_In {{STATE}}, as of {{MONTH AND DAY}}, {{GROUP}} had the highest risk of contracting COVID-19. {{GROUP}} were most likely to have died._

_In {{STATE}}, as of {{MONTH AND DAY}}, {{GROUP}} had the highest risk of contracting COVID-19 and were also most likely to have died._

* Slight variations for All states and District of Columbia:

 _In the District of Columbia, as of {{MONTH AND DAY}}, {{GROUP}} had the highest risk of contracting COVID-19. {{GROUP}} were most likely to have died._

_In the District of Columbia, as of {{MONTH AND DAY}}, {{GROUP}} had the highest risk of contracting COVID-19 and were also most likely to have died._

_Nationwide, as of {{MONTH AND DAY}}, {{GROUP}} had the highest risk of contracting COVID-19. {{GROUP}} were most likely to have died._

_Nationwide, as of {{MONTH AND DAY}}, {{GROUP}} had the highest risk of contracting COVID-19. {{GROUP}} were most likely to have died._

**For Table1 states (race/ethnicity combined), with the exception of Utah**
* Data comes from the Race Data Publishing spreadsheet, sheet: flattenedTable1
* Graphic footnote copy:

_**Notes:** {{STATE}} has reported race and ethnicity data for XX% of cases and YY% of deaths. Graphic only includes demographic groups reported by the state. Race categories are mutually exclusive and defined as not Hispanic or Latino._

**For Table2 states (race/ethnicity separate), with the exception of Wyoming**
* Data comes from the Race Data Publishing spreadsheet, sheet: flattenedTable2
* Graphic footnote copy:

_**Notes:** {{STATE}} has reported race data for XX% of cases and YY% of deaths, and ethnicity data for ZZ% of cases and WW% of deaths. Graphic only includes demographic groups reported by the state. Race categories are mutually exclusive and include both Hispanic/Latino and non-Hispanic/Latino ethnicity._

**For Nationwide, special case**
* Data comes from the Race Data Publishing spreadsheet, sheet: [API] flattened race combined (1), row: US
* Graphic header copy - 2 copy scenarios:

_**Notes:** Nationwide, XX of 56 states and territories report race/ethnicity information for cases and YY of 56 report race/ethnicity for deaths. Graphic includes demographic data from all states and territories that report, using standard Census categories where possible, and scaled to the total U.S. population for each Census category. Race categories may overlap with Hispanic/Latino ethnicity. Some rates are underestimated due to lack of reporting of race and ethnicity categories for COVID-19 cases and deaths._

**For Utah, special case to Table1 states**
* Only difference between Utah and other Table1 states is due to the footnote. All else is the same.
* Graphic footnote copy:

_Utah has reported race and ethnicity data for XX% of cases and XX% of deaths. Graphic only includes demographic groups reported by the state. Race categories are non-mutually-exclusive and are defined as not Hispanic or Latino._

**For Wyoming, special case to Table2 states**
* Only difference between Wyoming and other Table2 states is due to the footnote. All else is the same.
* Graphic footnote copy:

_Wyoming has reported race data for XX% of cases and YY% of deaths, and ethnicity data for ZZ% of cases and WW% of deaths. Graphic only includes demographic groups reported by the state. Race categories are non-mutually-exclusive and include both Hispanic/Latino and non-Hispanic/Latino ethnicity._

**For empty states, when there's 0 race/ethnicity data to show for both cases and deaths**
![Screen Shot 2020-09-18 at 5 20 56 PM](https://user-images.githubusercontent.com/22971446/93654608-3e7cbf80-f9d3-11ea-8182-f5842fde1eb3.png)

* Copy:

_As of {{MONTH AND DAY}}, {{STATE}} did not report race and ethnicity data._
_Help us get better data:_
_**www.covidtracking.com/race/get-better-data**_

**For empty states, when there's 0 race/ethnicity data to show for either cases or deaths**
![Screen Shot 2020-09-18 at 4 55 56 PM](https://user-images.githubusercontent.com/22971446/93653881-afba7380-f9cf-11ea-88b1-4679ab4030a0.png)
* Just hide the chart if it has 0 for all values

**For empty states, when there's data to show - but a specific race/ethnicity doesn't report any data**
![Screen Shot 2020-09-18 at 5 17 13 PM](https://user-images.githubusercontent.com/22971446/93654503-a67ed600-f9d2-11ea-9c44-4f09a0a0cd9c.png)
![Screen Shot 2020-09-18 at 5 20 56 PM](https://user-images.githubusercontent.com/22971446/93654599-3755b180-f9d3-11ea-9201-64865f76051b.png)
* Replace the bar with this empty state copy:

_No data reported_

**Comment by neeshabeee** [comment]
@schwartzadev Most of this is for record-keeping purposes, for future reference.

For you specifically, based on where we currently are in development, I'd check out these sections:
* The section entitled "Copy to use when referring to different racial and ethnic groups"
* The last section entitled: "Logic for the graphics & generated social media copy."

**Comment by schwartzadev** [comment]
Thanks so much @neeshabeee!

Most of these updates are now done in #1289.

Below are the only outstanding items:

**TODO**
- [ ] Add (All) card
  - [ ] make default selection
- [ ] Data comes from the Race Data Publishing spreadsheet, sheet: [API] flattened race combined (1), row: US


Header:
```
_Nationwide, as of {{MONTH AND DAY}}, {{GROUP}} had the highest risk of contracting COVID-19. {{GROUP}} were most likely to have died._
```

Footer:
```
_**Notes:** Nationwide, the United States has reported race and ethnicity data for XX% of cases and XX% of deaths. Graphic includes demographic data reported across all states, using standard Census categories where possible. Race categories include both Hispanic/Latino and non-Hispanic/Latino ethnicity._
```

- [ ] Adjust formatting so NHPI is on one line

**Launch**
- [ ] Add to global nav
