### ISSUE TITLE
OVERALL v2 LIST

### ISSUE THREAD

**Issue by kissane** [COVID19Tracking/website#245]
I…don't know how to use Github's weird project management features, so I'm going to do this old-school. Everything outstanding on the v2 site refresh should get an issue that gets tracked in here.

- [x] Launch plan—we need one, incl staffing #244

**Main design/dev pieces:**
- [x] Handle the homepage #151 (in [process](https://github.com/COVID19Tracking/website/pull/251))
- [x] Update the footer #259
- [x] Make the tables nice on mobile #208 
- [x] Handle page body design/template #239
- [x] Fonts tho #240
- [x] Make the site nav extra nice #254 
- [x] Colors! #256 

**Content/editorial:**
- [x] Why It Matters page #152
- [ ] Updated best practices doc #178
- [ ] Finish and add new state grades documentation #242

**Markup/design tweaks we probably missed:**
- [ ] Link to state data sources from individual state pages #141

**Loose ends issues to check/close before we go live:**
- [x] Test Netlify CMS in new stack #241
- [x] Make sure we got all those nice press logos #206 (in [process](https://github.com/COVID19Tracking/website/pull/252))
- [x] We back in tables? #200
- [x] Got the outcomes data in? #177
- [x] Update Twitter/social preview card with the new logo/design #253

**Tabled**
- [ ] Get a friendly branch off the data dashboard visualization PR going #243

**Comment by pspeter3** [comment]
I've been really impressed by what COVID Tracking is doing and would love to help. Any issues you would like to assign?

**Comment by kissane** [comment]
> I've been really impressed by what COVID Tracking is doing and would love to help. Any issues that I can help tackle for v2?

YES, Slack invitation incoming.

**Comment by kissane** [comment]
Or actually, @pspeter3, could you send me your best email? erin@incisive.nu is me, I'll get you into the project's website design/dev Slack channels.

**Comment by pspeter3** [comment]
Thanks, sent you an email. Looking forward to helping!

**Comment by kevee** [comment]
Hm, what should go here? https://gatsbyjs--upbeat-lovelace-3e9fff.netlify.com/project

**Comment by kissane** [comment]
Closing this, will chase down the remaining items separately.
