### ISSUE TITLE
Design-related items in current v2 build

### ISSUE THREAD

**Issue by beep** [COVID19Tracking/website#276]
Just logging a few design-related things I’ve spotted on [the current preview site](https://gatsbyjs--upbeat-lovelace-3e9fff.netlify.com/data), and comparing it to [the v2 comps](https://www.dropbox.com/s/41azsi92oh724m6/covidrefresh%20-%202020%200330%20EM.sketch?dl=0). Please note that these are _all_ for discussion/review, to see what’s worth fixing before launch!

(Also, happy to break these out into smaller issues if need be.)

## Global

(Taking a stab at moving a few of these into priority buckets, but these are totally subjective assignments and up for discussion!)

### High priority

- [x] - We’d aimed for a max-width of 1140px / 71.25rem in the comps; it’d be great to get that in place.
- [x] - Related to that, the widths of the header, content, and footer areas should be in alignment across all viewports. (Basically if they can share the same margins / max-width, ` COOL `.)
- [x] - The font stack seems to be rendering out simply as `sans-serif`; here’s [the stack I believe we’re aiming for](https://covid-tracking.slack.com/archives/C010N48RY73/p1585594269114000).

### Important, perhaps not blockers:

- Hover and focus styles seem to be missing on links.
- [x] Generally, line-height feels pretty generous in the content area; might be worth taking a look at the values in the comps, and lining them up with the code?

## Navigation

- Small-screen view:

- [x]   - Can we add `cursor: pointer` to the menu toggle?
- [x]   - Tiny accessibility thing: can we add an `aria-expanded="false"` to the button when the menu’s closed, and `aria-expanded="false"` when it’s opened?

- [x]   - Padding underneath the page title is a little generous. ([Screenshot](https://www.dropbox.com/s/877puqcahx4f2t6/nav%20-%20mobile%20padding.png?dl=0))
- [x] - The “active” border’s spec’d to be 5px tall, and it needs a few pixels of padding between it and the link text. ([Screenshot](https://www.dropbox.com/s/p9j8eptsd5i5ljy/nav%20-%20active%20bar.png?dl=0))
- [ ] - I might be misreading the site hierarchy, but I think the active navigation state seems to be getting lost on a few “sub” pages. (For example, click on “FAQs for Newsrooms”, and it’s active; click over to “About the project”, and the bar’s removed from the “FAQs for Newsrooms” link.)

## Homepage

- Intro block:
  - [x] The header text is a little larger than spec’d on widescreen. (Currently at 48px with a 1.3 line-height, should be 40px at 1.25.) I dig the 24px at 1.25 on smaller screens, but can it extend to a breakpoint wider than 480px?
  - [x] Font-sizing on the button + “learn more” link is a little smaller than spec’d.
- [x] - Logo block:
- [x] - I think we’d decided on a white background for this block, and a max-height of 40px for the logos.
- [x] - Content question: in the comp, we’d settled on The A, NYT, ProPublica, Vox, WaPo, CNN, and WSJ for the homepage. Is what’s shown on the dev site the correct order? (FIXED)
- Visualization gallery:
  - [x] We’d moved the gray background down to this module in the comp, with some light borders to offset it.
  - [x] Might suggest double-checking the type settings here as well? (The source text should be italicized and a lighter gray.)
- Why this data matters / In the news
  - [x] Maybe double-check the type styles here? (Currently, both columns are typeset at the same size; source text for articles should be italicized and a lighter gray
  - [x] Spacing around the arrowed list is currently a little more generous than spec’d.

## [Data page](https://gatsbyjs--upbeat-lovelace-3e9fff.netlify.com/data/)

- The individual states are showing the old content/tables, I believe, and still appearing in a two-column layout.

## [State page](https://gatsbyjs--upbeat-lovelace-3e9fff.netlify.com/data/state/alaska)

- Same notes here; looks like the page order & tables haven’t been updated yet.

**Comment by kevee** [comment]
@schwartzadev You wanna take on the Data/state page tables (because you love tables now) and I'll start from the top

**Comment by kevee** [comment]
I'm seeing the font stack in there, but I could be missing something:

![image](https://user-images.githubusercontent.com/270536/78040966-27231a80-733e-11ea-9a8a-10cebc3645d7.png)

**Comment by jasonsantamaria** [comment]
Some color recs:

- [ ] Text link color should be `#575AAD` and I suggest `#8B8DC7` for a hover/active color
- [ ] Button bg should be `#8CC7F4` and `#E2F1FC` for a hover/active color
- [ ] Nav link hovers can be the same as the "active" state (blue bottom border)

**Comment by kevee** [comment]
Colors in https://github.com/COVID19Tracking/website/pull/277/commits/a1ad74d0d387ebbcab249d0f2e14f80a35bab1a4

**Comment by kevee** [comment]
Where we are at right now: https://5e836511afdc600006e20311--upbeat-lovelace-3e9fff.netlify.com/

**Comment by jasonsantamaria** [comment]
> Where we are at right now: https://5e836511afdc600006e20311--upbeat-lovelace-3e9fff.netlify.com/

A couple of updates that may have gotten garbled:

- [ ] Nav link hovers: `#E2F1FC` and blue bottom border from active state
- [ ] Hovers for text links: `#8B8DC7`
- [ ] Hover for the white text link in hero: `#E2F1FC`
- [ ] Can all hover styles ease on ~`.2s`?
- [ ] Looks like the ProPub logo is missing the magnifying glass which is making it a lot bigger

**Comment by schwartzadev** [comment]
Oh yeah I _love_ tables 😄 

I can tackle those, sure.


> The individual states are showing the old content/tables, I believe, and still appearing in a two-column layout.

@beep : The new outcomes data isn't yet available on the API, so I dropped those columns last night. After doing that, there was a _ton_ of white space so I re-added the two column layout only on very large viewports. See #268 .

> Same notes here; looks like the page order & tables haven’t been updated yet.

See above @ the outcomes data...are there changes that you'd like to see considering that data isn't yet available?

**Comment by beep** [comment]
@schwartzadev if you need a cool bio for slack, may i humbly suggest this 😂

<img width="182" alt="image" src="https://user-images.githubusercontent.com/124493/78057062-1bdae980-7354-11ea-8670-9a453461578f.png">

But seriously, that’s real helpful—thanks for calling that out. And [per our chat in Slack](https://covid-tracking.slack.com/archives/C010N48RY73/p1585675301302200?thread_ts=1585674969.300200&cid=C010N48RY73), it sounds like the new outcomes data likely _won’t_ be coming before tomorrow, so we should probably treat it as a post-launch item. (Unless @kissane feels otherwise!)

> are there changes that you'd like to see considering that data isn't yet available?

Some small suggestions, none of which are critical!

- Let’s remove the `line-height` of 1.8rem on the tables, and bring the font size down a tad. (Maybe `0.85em`?)
- We can probably remove the `font-size: 1.1em` on the `[colgroup]` headers until we’ve got outcomes data.
- We can probably drop the `margin-bottom: calc(1.8rem / 2)` on `li` elements. (Hm—globally, I think?)
- Looks like there’s a slight alignment jog moving into the States section. ([Screenshot](https://www.dropbox.com/s/8w0g8lrohrugahd/data%20-%20table%20alignment.png?dl=0))

Thank you, Andrew!

**Comment by beep** [comment]
(Oh, and we can drop the `col` / `colgroup` elements we can sync them up with the outcomes data structure.)

**Comment by schwartzadev** [comment]
The latest from Slack: we will move the outcomes data to a **post-v2 launch item** (updating here for transparency)

**Comment by schwartzadev** [comment]
@beep -- #291 should take care of your suggestions 👍

**Comment by schwartzadev** [comment]
Hey @jasonsantamaria #296 will close this :wink:

**Comment by jasonsantamaria** [comment]
> Hey @jasonsantamaria #296 will close your suggestions 😉

Ack, sorry still not quite done — looks like a few things are missing/bugged:

Nav links, I'll break all states down to avoid confusion:
<img width="780" alt="Screen Shot 2020-03-31 at 10 00 50 PM" src="https://user-images.githubusercontent.com/128280/78091533-1e146680-739b-11ea-8304-ac98e93605b8.png">

And the big CTA button hover styles are bugging out and hiding the text.  Button bg should be `#8CC7F4` and `#E2F1FC` for a hover/active color, and the text can remain `#012656` on all states.

**Comment by schwartzadev** [comment]
> I might be misreading the site hierarchy, but I think the active navigation state seems to be getting lost on a few “sub” pages. (For example, click on “FAQs for Newsrooms”, and it’s active; click over to “About the project”, and the bar’s removed from the “FAQs for Newsrooms” link.)

I'm going to add this to a new issue for clarity and close this one

**Comment by schwartzadev** [comment]
@jasonsantamaria I haven't forgotten about your updates -- I'm moving it to a new issue for clarity
