### ISSUE TITLE
New "Contact Us" Page

### ISSUE THREAD

**Issue by jdmaresco** [COVID19Tracking/website#818]
# Overview

We are looking to create a new Contact Us page for people to route their support inquiries to the right place. We will use a form that submits directly to Front (our help desk tool), where the message will be routed to the right inbox based on the option selected in a dropdown field.

# TODO
- [x] Design team provide styling guidance / mock
  - [x] "What are you contacting us about?" should be a select field/dropdown
- [x] Build new page and host at `/contact`
  - [x] Work with @jdmaresco to run a test and figure out how to route the message to the right inbox based on what option the user selects in an input field
- [x] Route to `/contact/success` if form submitted successfully
- [x] Route to `/contact/error` if form not submitted successfully

# Page Copy

Thanks for your interest in our work! 

* If you want to volunteer, see [how you can help](/about/project/help).
* If you are a journalist who needs help using our data, please fill out our [data-user intake form]. We’ll invite you to join a Slack where you can post questions and get help. 

For everything else, please email support@covidtracking.com or fill out the form below. 

Please note that we receive a high volume of inquiries, and as a volunteer project, we have limited resources. We are logging all feedback and making constant improvements to how we collect and present data, but we are only able to reply to a small number of inquiries.   

What are you contacting us about?
* I want to report an issue with your data
* I want to report an issue with the website or web accessibility
* I have questions about state data grades
* I have feedback on the COVID Racial Data Tracker
* I'm a journalist with a media inquiry  
* Something else!

Name

Email address 

Message

Submit 

# Success Page

Thanks for contacting us! Please note that we review and log all feedback, but we cannot reply to all inquiries.       

# Boilerplate Form Code (Provided by Front)

```
<form
  method="POST"
  name="fa-form-1"
  action="https://webhook.frontapp.com/forms/c3c09a5603c02d2b7f86/KU--_qKvaSkUZHR2T92KQZ8hy5TatxTkRexeSE4NtpFltSVYROQxxbkIdSNH3RcHlZUI4RGGlHL7NwDr00Ki8WMFSOoBBMmgZ28PppSbXx-SQVi51ogAj28bbn6M"
  enctype="multipart/form-data"
  accept-charset="utf-8"
>
  <div>
    <label for="name">Name</label>
    <input type="text" name="name">
  </div>

  <div>
    <label for="email">Email</label>
    <input type="email" name="email">
  </div>

  <div>
    <textarea name="body"></textarea>
  </div>

  <div>
    <input type="file" name="attachment">
  </div>

   <div id="html_element"></div>
  <div>
    <input type="submit" value="Send">
  </div>
</form>
```

**Comment by kevee** [comment]
@jdmaresco we already have https://covidtracking.com/contact/success, can we use that instead of `contact-success`?

**Comment by jdmaresco** [comment]
yes, I just need to update the callback URL in Front

**Comment by kevee** [comment]
Do you want recaptcha on this?

**Comment by jdmaresco** [comment]
Probably.

**Comment by kevee** [comment]
Contact page is up, there's an issue with Front not liking our referrer, I'm checking:

https://deploy-preview-820--upbeat-lovelace-3e9fff.netlify.app/contact

**Comment by jdmaresco** [comment]
Cool. Yeah I got an error when trying to submit from the form at the URL above.

**Comment by kevee** [comment]
OK referrer error fixed:

https://deploy-preview-820--upbeat-lovelace-3e9fff.netlify.app/contact

![image](https://user-images.githubusercontent.com/270536/81410636-102ad180-910f-11ea-923f-8094e3796234.png)

**Comment by kevee** [comment]
Note: We can also [change these form fields](https://help.frontapp.com/t/h429xa/how-to-set-up-a-form-inbox-in-front#autoreply-support) to switch the target inbox

**Comment by jdmaresco** [comment]
@kevee can you make sure the "success" page matches the copy Sara provided (see above)

**Comment by jdmaresco** [comment]
Since we are likely going to hit "reply," it feels non-ideal that the IP address is logged in the body. Can you remove that?

![image](https://user-images.githubusercontent.com/1327983/81447575-e1325100-914a-11ea-89a2-9d6df29accfc.png)

**Comment by kevee** [comment]
The IP thing is in Front, I'll remove that.

**Comment by kevee** [comment]
I updated the success page.
